-- ═══════════════════════════════════════════════════════════════════
-- AI Meeting Notes: auto-detect Teams meetings, pull transcripts,
-- generate minutes + action items via Claude AI
-- ═══════════════════════════════════════════════════════════════════

-- Meeting notes generated by AI from transcripts
CREATE TABLE IF NOT EXISTS meeting_notes_ai (
  id BIGSERIAL PRIMARY KEY,
  -- Source meeting info (from Graph calendar)
  calendar_event_id TEXT UNIQUE,           -- Graph event ID to avoid duplicates
  title TEXT NOT NULL,
  meeting_date TIMESTAMPTZ NOT NULL,
  meeting_end TIMESTAMPTZ,
  organizer TEXT,                           -- email of organizer
  attendees JSONB DEFAULT '[]',            -- [{email, name}]
  teams_meeting_url TEXT,

  -- Transcript
  transcript_text TEXT,                     -- raw transcript (auto or manually pasted)
  transcript_source TEXT DEFAULT 'manual',  -- 'teams_auto', 'manual', 'upload'

  -- AI-generated content
  summary TEXT,                             -- executive summary
  minutes_html TEXT,                        -- formatted meeting minutes
  key_decisions JSONB DEFAULT '[]',        -- [{decision, context}]
  action_items JSONB DEFAULT '[]',         -- [{task, assignee, due_date, status}]

  -- Processing status
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'transcript_ready', 'processing', 'completed', 'failed', 'no_transcript')),
  error_message TEXT,
  processed_at TIMESTAMPTZ,
  email_sent BOOLEAN DEFAULT FALSE,
  email_sent_at TIMESTAMPTZ,

  -- Meta
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for cron lookups
CREATE INDEX IF NOT EXISTS idx_meeting_notes_ai_status ON meeting_notes_ai(status);
CREATE INDEX IF NOT EXISTS idx_meeting_notes_ai_date ON meeting_notes_ai(meeting_date DESC);
CREATE INDEX IF NOT EXISTS idx_meeting_notes_ai_event ON meeting_notes_ai(calendar_event_id);

-- Action items checklist (normalized for dashboard tracking)
CREATE TABLE IF NOT EXISTS meeting_action_items (
  id BIGSERIAL PRIMARY KEY,
  meeting_note_id BIGINT NOT NULL REFERENCES meeting_notes_ai(id) ON DELETE CASCADE,
  task TEXT NOT NULL,
  assignee TEXT,                  -- name or email
  assignee_user_id TEXT,          -- linked user id if matched
  due_date DATE,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'completed')),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_meeting_action_items_note ON meeting_action_items(meeting_note_id);
CREATE INDEX IF NOT EXISTS idx_meeting_action_items_status ON meeting_action_items(status);
CREATE INDEX IF NOT EXISTS idx_meeting_action_items_assignee ON meeting_action_items(assignee_user_id);
