import { supabaseAdmin } from '../_lib/supabase-admin.js';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  const { period } = req.body || {};

  try {
    // Get timesheet summary
    const { data: summary } = await supabaseAdmin.rpc('get_timesheet_summary', { p_period: period || null });

    // Get all timesheets for period with entries
    let query = supabaseAdmin
      .from('timesheets')
      .select('*, timesheet_entries(*), users(name, project, hourly_rate)');
    if (period) query = query.eq('period_label', period);
    const { data: timesheets } = await query;

    // Get leave summary
    const { data: leaveSummary } = await supabaseAdmin.rpc('get_leave_summary');

    // Build consolidated HTML
    const reportHtml = buildReportHtml(summary, timesheets, leaveSummary, period);

    // Store report
    const { data: report } = await supabaseAdmin.from('consolidation_reports').insert({
      report_type: 'consolidated',
      period,
      data: { summary, timesheetCount: timesheets?.length || 0 },
      generated_by: req.body.generatedBy || 'system',
    }).select().single();

    return res.status(200).json({
      success: true,
      reportId: report?.id,
      summary,
      html: reportHtml,
    });
  } catch (err) {
    return res.status(500).json({ error: err.message });
  }
}

function buildReportHtml(summary, timesheets, leaveSummary, period) {
  const rows = (summary || []).map(s => `
    <tr>
      <td style="border:1px solid #e2e8f0;padding:8px;">${s.project}</td>
      <td style="border:1px solid #e2e8f0;padding:8px;text-align:center;">${s.employee_count}</td>
      <td style="border:1px solid #e2e8f0;padding:8px;text-align:center;">${s.submitted_count}</td>
      <td style="border:1px solid #e2e8f0;padding:8px;text-align:right;">${Number(s.total_hours).toFixed(1)}</td>
    </tr>
  `).join('');

  return `
    <html><head><style>
      body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
      h1 { color: #1e3a5f; }
      table { width: 100%; border-collapse: collapse; margin: 20px 0; }
      th { background: #f1f5f9; border: 1px solid #e2e8f0; padding: 10px; text-align: left; }
    </style></head>
    <body>
      <h1>Consolidated Timesheet Report</h1>
      <p><strong>Period:</strong> ${period || 'All'}</p>
      <p><strong>Generated:</strong> ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
      <h2>Summary by Project</h2>
      <table>
        <thead><tr>
          <th>Project</th><th>Employees</th><th>Submitted</th><th>Total Hours</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>
      <p style="color:#666;font-size:12px;margin-top:40px;">Generated by VCC Timesheet System</p>
    </body></html>
  `;
}
